# 라이브러리 불러오기

In [84]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder   # 사이킷런 - 전처리 모듈 -> 레이블인코더, 원핫인코더

### 데이터 불러오기

In [85]:
csv_PATH = 'Clean_Dataset.csv'
df_origin = pd.read_csv(csv_PATH)

df_origin.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [86]:
df_origin = df_origin.drop('Unnamed: 0', axis=1)    # 컬럼(Unnamed: 0) 삭제
df_origin.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

### 레이블 인코딩
- 범주형 데이터(문자열 데이터)에 숫자를 순서대로 매기는 방식
- 판다스와 사이킷런 모두 활용 가능

### 판다스에서 레이블 인코딩하기 - pd.factorize()

In [87]:
df= df_origin.copy()    # 데이터프레임 복사
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  str
 1   flight            300153 non-null  str
 2   source_city       300153 non-null  str
 3   departure_time    300153 non-null  str
 4   stops             300153 non-null  str
 5   arrival_time      300153 non-null  str
 6   destination_city  300153 non-null  str
 7   class             300153 non-null  str
 8   duration          300153 non-null  float64
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: float64(1), int64(2), str(8)
memory usage: 40.6 MB

In [88]:
df['airline'].value_counts()

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [89]:
pd.factorize(df['airline'])[0]

array([0, 0, 1, ..., 2, 2, 2], shape=(300153,))

In [90]:
df.shape    # 행 개수, 열 개수

(300153, 11)

### .reshape(-1,1)
- 1차원 배열을 (행 수, 1) 형태의 2차원으로 바꿔서 데이터프레임의 새 컬럼으로 대입하기 쉽게 한다

In [91]:
pd.factorize(df['airline'])[0].reshape(-1,1)    # 2차원

array([[0],
       [0],
       [1],
       ...,
       [2],
       [2],
       [2]], shape=(300153, 1))

In [92]:
df['label_encoding'] = pd.factorize(df['airline'])[0].reshape(-1,1)
df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2

### 사이킷런으로 레이블 인코딩하기 - LabelEncoder(알파벳 순서로)

### fit_transform()
- fit : 범주(문자열) 학습
- transform : 숫자 변환
- 학습하고 숫자변환을 한 번에 수행

In [93]:
le = LabelEncoder()
le.fit_transform(df['airline'])

array([4, 4, 0, ..., 5, 5, 5], shape=(300153,))

In [94]:
pd.set_option('display.max_columns', None)  # 컬롬이 많아도 잘리지 않고 다 보이게 설정

In [95]:
df['airline_Label_Encoder'] = le.fit_transform(df['airline'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_Label_Encoder
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5

#### 레이블 인코딩 역변환(디코딩)하기 - .inverse_transform()

In [96]:
le.inverse_transform(df['airline_Label_Encoder'])

df.head()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,label_encoding,airline_Label_Encoder
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,0,4
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,0,4
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,1,0
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,2,5
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,2,5

### 원 핫 인코딩
- 레이블 인코딩 시 문제점이 의도치 않게 숫자 크기 정보가 생겨서 이를 크기 순서로 오해할 경우가 있다.
- 이 문제를 해결하기 위해 원핫 인코딩이 등장
- 각 범주(문자열)를 독립된 0 또는 1 컬럼으로 분리한다.
- 범주 개수가 많아지면 컬럼 수가 급증하는 트레이드오프가 있다.
- 범주 개수가 적으면 원핫 인코딩을 추천, 많을 떄는 신중히 판단을 한다.

### 판다스에서 원핫 인코딩하기 - pd.get_dummies()

In [97]:
df = df_origin.copy()

In [98]:
# class 컬럼을 원핫 인코딩
pd.get_dummies(df['class'])

        Business  Economy
0          False     True
1          False     True
2          False     True
3          False     True
4          False     True
...          ...      ...
300148      True    False
300149      True    False
300150      True    False
300151      True    False
300152      True    False

[300153 rows x 2 columns]

In [ ]:
df = pd.get_dummies(df['class'])   # 'class 속성만 원핫 인코딩'
df.head()

   Business  Economy
0     False     True
1     False     True
2     False     True
3     False     True
4     False     True

In [100]:
df2 = df_origin.copy()

In [101]:
df2 = pd.get_dummies(df2)   # df2라는 데이터프레임 전체(범주형 컬럼 다 해당) 원핫 인코딩
df2.head()

,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,flight_6E-102,flight_6E-105,flight_6E-113,flight_6E-121,flight_6E-123,flight_6E-126,flight_6E-128,flight_6E-131,flight_6E-132,flight_6E-134,flight_6E-135,flight_6E-136,flight_6E-138,flight_6E-139,flight_6E-146,flight_6E-148,flight_6E-149,flight_6E-151,flight_6E-152,flight_6E-153,flight_6E-154,flight_6E-156,flight_6E-157,flight_6E-161,flight_6E-164,flight_6E-165,flight_6E-168,flight_6E-171,flight_6E-172,flight_6E-176,flight_6E-177,flight_6E-179,flight_6E-181,flight_6E-183,flight_6E-184,flight_6E-186,flight_6E-188,flight_6E-192,flight_6E-193,flight_6E-198,flight_6E-199,flight_6E-2001,flight_6E-2005,flight_6E-2007,flight_6E-2008,flight_6E-2009,flight_6E-201,flight_6E-2013,flight_6E-2015,flight_6E-2016,flight_6E-2022,flight_6E-2025,flight_6E-2026,flight_6E-2027,flight_6E-2028,flight_6E-2031,flight_6E-2032,flight_6E-2033,flight_6E-2034,flight_6E-2036,flight_6E-2042,flight_6E-2043,flight_6E-2046,flight_6E-2047,flight_6E-2048,flight_6E-205,flight_6E-2053,flight_6E-2054,flight_6E-2057,flight_6E-2061,flight_6E-2062,flight_6E-2065,flight_6E-2069,flight_6E-207,flight_6E-2076,flight_6E-2077,flight_6E-208,flight_6E-2081,flight_6E-2082,flight_6E-2083,flight_6E-2087,flight_6E-2089,flight_6E-2092,flight_6E-2093,flight_6E-2097,flight_6E-2102,flight_6E-2103,flight_6E-2106,flight_6E-2107,flight_6E-2109,flight_6E-212,flight_6E-2127,flight_6E-213,flight_6E-2131,flight_6E-2137,flight_6E-2147,flight_6E-2148,flight_6E-2154,flight_6E-2162,flight_6E-2168,flight_6E-2169,flight_6E-2172,flight_6E-2174,flight_6E-2176,flight_6E-2178,flight_6E-218,flight_6E-2181,flight_6E-2186,flight_6E-2188,flight_6E-219,flight_6E-2193,flight_6E-221,flight_6E-224,flight_6E-2247,flight_6E-2248,flight_6E-2249,flight_6E-227,flight_6E-2274,flight_6E-232,flight_6E-2329,flight_6E-2331,flight_6E-2336,flight_6E-2337,flight_6E-2338,flight_6E-234,flight_6E-2343,flight_6E-2346,flight_6E-2348,flight_6E-2349,flight_6E-236,flight_6E-2367,flight_6E-2373,flight_6E-244,flight_6E-245,flight_6E-2456,flight_6E-246,flight_6E-2471,flight_6E-2474,flight_6E-2478,flight_6E-2479,flight_6E-248,flight_6E-2485,flight_6E-251,flight_6E-2511,flight_6E-2513,flight_6E-2514,flight_6E-2516,flight_6E-2517,flight_6E-2518,flight_6E-2519,flight_6E-255,flight_6E-261,flight_6E-2615,flight_6E-2616,flight_6E-2618,flight_6E-266,flight_6E-268,flight_6E-2685,flight_6E-269,flight_6E-271,flight_6E-2719,flight_6E-274,flight_6E-2752,flight_6E-2753,flight_6E-276,flight_6E-2763,flight_6E-2769,flight_6E-282,flight_6E-283,flight_6E-2841,flight_6E-2843,flight_6E-285,flight_6E-286,flight_6E-289,flight_6E-2901,flight_6E-2914,flight_6E-292,flight_6E-2938,flight_6E-2939,flight_6E-294,flight_6E-295,flight_6E-296,flight_6E-298,flight_6E-307,flight_6E-308,flight_6E-309,flight_6E-312,flight_6E-318,flight_6E-319,flight_6E-321,flight_6E-3211,flight_6E-3214,flight_6E-327,flight_6E-331,flight_6E-332,flight_6E-345,flight_6E-353,flight_6E-354,flight_6E-356,flight_6E-357,flight_6E-358,flight_6E-363,flight_6E-365,flight_6E-368,flight_6E-369,flight_6E-371,flight_6E-374,flight_6E-375,flight_6E-379,flight_6E-384,flight_6E-387,flight_6E-394,flight_6E-395,flight_6E-397,flight_6E-398,flight_6E-401,flight_6E-404,flight_6E-408,flight_6E-409,flight_6E-413,flight_6E-415,flight_6E-416,flight_6E-417,flight_6E-425,flight_6E-426,flight_6E-434,flight_6E-436,flight_6E-438,flight_6E-439,flight_6E-442,flight_6E-448,flight_6E-453,flight_6E-455,flight_6E-457,flight_6E-461,flight_6E-469,flight_6E-477,flight_6E-478,flight_6E-483,flight_6E-484,flight_6E-487,flight_6E-488,flight_6E-489,flight_6E-495,flight_6E-496,flight_6E-5001,flight_6E-5002,flight_6E-5003,flight_6E-5006,flight_6E-5007,flight_6E-5012,flight_6E-5013,flight_6E-5014,flight_6E-5016,flight_6E-5017,flight_6E-5018,flight_6E-502,flight_6E-5026,flight_6E-503,flight_6E-5031,flight_6E-5037,flight_6E-5038,flight_6E-5041,flight_6E-5042,flight_6E-5047,flight_6E-5059,flight_6E-5063,flight_6E-5071,flight_6E-5073,flight_6E-5087,flight_6E-5088,flight_6E-512,flight_6E-514,flight_6E-515,flight_6E-5175,flight_6E-5176,flight_6E-519,flight_6E-5202,flight_6E-5203,flight_6E-5206,flight_6E-5207,flight_6E-5208,flight_6E-5209,flight_6E-5211,flight_6E-5214,flight_6E-5217,flight_6E-5218,flight_6E-5236,flight_6E-524,flight_6E-528,flight_6E-5302,flight_6E-5303,flight_6E-5305,flight_6E-5307,flight_6E-5308,flight_6E-531,flight_6E-5312,flight_6E-5313,flight_6E-5316,flight_6E-5317,flight_6E-5323,flight_6E-5325,flight_6E-5327,flight_6E-5328,flight_6E-5329,flight_6E-533,flight_6E-5331,flight_6E-5332,flight_6E-5336,flight_6E-5337,flight_6E-5338,flight_6E-534,flight_6E-5342,flight_6E-5343,flight_6E-5344,flight_6E-5345,flight_6E-5347,flight_6E-5349,flight_6E-5352,flight_6E-5355,flight_6E-5358,flight_6E-5359,flight_6E-5361,flight_6E-5365,flight_6E-5366,flight_6E-5367,flight_6E-5368,flight_6E-5369,flight_6E-537,flight_6E-5371,flight_6E-5372,flight_6E-5373,flight_6E-5375,flight_6E-5376,flight_6E-5379,flight_6E-5381,flight_6E-5382,flight_6E-5384,flight_6E-5386,flight_6E-5389,flight_6E-539,flight_6E-5391,flight_6E-5392,flight_6E-5393,flight_6E-5394,flight_6E-5395,flight_6E-5396,flight_6E-5398,flight_6E-5399,flight_6E-541,flight_6E-542,flight_6E-543,flight_6E-5431,flight_6E-544,flight_6E-546,flight_6E-549,flight_6E-5501,flight_6E-552,flight_6E-557,flight_6E-559,flight_6E-561,flight_6E-562,flight_6E-563,flight_6E-566,flight_6E-573,flight_6E-574,flight_6E-575,flight_6E-581,flight_6E-584,flight_6E-588,flight_6E-591,flight_6E-595,flight_6E-599,flight_6E-6004,flight_6E-6006,flight_6E-6007,flight_6E-6012,flight_6E-6014,flight_6E-6016,flight_6E-6017,flight_6E-6021,flight_6E-6023,flight_6E-6029,flight_6E-605,flight_6E-6051,flight_6E-606,flight_6E-6062,flight_6E-6066,flight_6E-6067,flight_6E-607,flight_6E-6084,flight_6E-6085,flight_6E-6086,flight_6E-6087,flight_6E-6088,flight_6E-6094,flight_6E-6095,flight_6E-6096,flight_6E-6098,flight_6E-6104,flight_6E-6106,flight_6E-6109,flight_6E-611,flight_6E-6111,flight_6E-6113,flight_6E-6121,flight_6E-6123,flight_6E-6128,flight_6E-613,flight_6E-6137,flight_6E-6139,flight_6E-6148,flight_6E-6151,flight_6E-6171,flight_6E-6172,flight_6E-6174,flight_6E-6178,flight_6E-6182,flight_6E-6183,flight_6E-6186,flight_6E-6187,flight_6E-6189,flight_6E-6195,flight_6E-6197,flight_6E-6198,flight_6E-6201,flight_6E-6202,flight_6E-6205,flight_6E-6206,flight_6E-621,flight_6E-6211,flight_6E-6212,flight_6E-6213,flight_6E-6214,flight_6E-6215,flight_6E-6216,flight_6E-6217,flight_6E-6219,flight_6E-6222,flight_6E-6223,flight_6E-6227,flight_6E-6231,flight_6E-6233,flight_6E-6234,flight_6E-6238,flight_6E-6242,flight_6E-6245,flight_6E-6247,flight_6E-6257,flight_6E-6258,flight_6E-626,flight_6E-6261,flight_6E-6264,flight_6E-6268,flight_6E-6269,flight_6E-627,flight_6E-6271,flight_6E-6277,flight_6E-6278,flight_6E-6282,flight_6E-6292,flight_6E-6293,flight_6E-6294,flight_6E-6307,flight_6E-6309,flight_6E-6319,flight_6E-6324,flight_6E-6326,flight_6E-6339,flight_6E-634,flight_6E-6344,flight_6E-6345,flight_6E-635,flight_6E-6358,flight_6E-6366,flight_6E-638,flight_6E-6381,flight_6E-6386,flight_6E-6393,flight_6E-6417,flight_6E-643,flight_6E-6433,flight_6E-6444,flight_6E-6445,flight_6E-6463,flight_6E-6464,flight_6E-6467,flight_6E-6474,flight_6E-6475,flight_6E-6478,flight_6E-6479,flight_6E-6488,flight_6E-6491,flight_6E-6505,flight_6E-6513,flight_6E-6515,flight_6E-6517,flight_6E-6535,flight_6E-654,flight_6E-6553,flight_6E-6565,flight_6E-6567,flight_6E-6572,flight_6E-6591,flight_6E-6593,flight_6E-6597,flight_6E-6612,flight_6E-6613,flight_6E-6616,flight_6E-6623,flight_6E-6636,flight_6E-668,flight_6E-6684,flight_6E-6717,flight_6E-6719,flight_6E-6721,flight_6E-6722,flight_6E-6737,flight_6E-6739,flight_6E-6741,flight_6E-6749,flight_6E-6753,flight_6E-676,flight_6E-6781,flight_6E-6785,flight_6E-6798,flight_6E-6802,flight_6E-6809,flight_6E-6815,flight_6E-6817,flight_6E-6818,flight_6E-6825,flight_6E-684,flight_6E-6865,flight_6E-6876,flight_6E-6891,flight_6E-6893,flight_6E-6897,flight_6E-6915,flight_6E-6917,flight_6E-6926,flight_6E-6939,flight_6E-695,flight_6E-6965,flight_6E-6971,flight_6E-698,flight_6E-6993,flight_6E-702,flight_6E-7062,flight_6E-7071,flight_6E-7076,flight_6E-708,flight_6E-7084,flight_6E-711,flight_6E-7114,flight_6E-7115,flight_6E-7118,flight_6E-7121,flight_6E-7127,flight_6E-713,flight_6E-7136,flight_6E-7141,flight_6E-7147,flight_6E-7149,flight_6E-715,flight_6E-7156,flight_6E-716,flight_6E-7175,flight_6E-7177,flight_6E-7183,flight_6E-7185,flight_6E-7193,flight_6E-7195,flight_6E-7201,flight_6E-7202,flight_6E-7204,flight_6E-7208,flight_6E-7211,flight_6E-7216,flight_6E-7221,flight_6E-7223,flight_6E-7224,flight_6E-7227,flight_6E-7234,flight_6E-725,flight_6E-7252,flight_6E-7257,flight_6E-7259,flight_6E-7261,flight_6E-7264,flight_6E-727,flight_6E-7271,flight_6E-7288,flight_6E-7292,flight_6E-7293,flight_6E-7298,flight_6E-7307,flight_6E-7329,flight_6E-7336,flight_6E-7348,flight_6E-735,flight_6E-736,flight_6E-738,flight_6E-739,flight_6E-7403,flight_6E-7407,flight_6E-743,flight_6E-747,flight_6E-751,flight_6E-752,flight_6E-755,flight_6E-7561,flight_6E-757,flight_6E-7583,flight_6E-7587,flight_6E-7589,flight_6E-759,flight_6E-761,flight_6E-7623,flight_6E-767,flight_6E-7713,flight_6E-772,flight_6E-781,flight_6E-782,flight_6E-788,flight_6E-793,flight_6E-796,flight_6E-798,flight_6E-802,flight_6E-804,flight_6E-806,flight_6E-807,flight_6E-809,flight_6E-811,flight_6E-818,flight_6E-821,flight_6E-822,flight_6E-825,flight_6E-827,flight_6E-832,flight_6E-841,flight_6E-847,flight_6E-848,flight_6E-854,flight_6E-855,flight_6E-856,flight_6E-864,flight_6E-865,flight_6E-866,flight_6E-869,flight_6E-871,flight_6E-875,flight_6E-879,flight_6E-881,flight_6E-882,flight_6E-884,flight_6E-886,flight_6E-887,flight_6E-889,flight_6E-892,flight_6E-893,flight_6E-895,flight_6E-897,flight_6E-898,flight_6E-903,flight_6E-905,flight_6E-907,flight_6E-911,flight_6E-912,flight_6E-913,flight_6E-917,flight_6E-922,flight_6E-926,flight_6E-927,flight_6E-929,flight_6E-932,flight_6E-938,flight_6E-939,flight_6E-943,flight_6E-944,flight_6E-945,flight_6E-947,flight_6E-949,flight_6E-951,flight_6E-952,flight_6E-954,flight_6E-958,flight_6E-959,flight_6E-961,flight_6E-963,flight_6E-966,flight_6E-967,flight_6E-969,flight_6E-972,flight_6E-973,flight_6E-975,flight_6E-978,flight_6E-982,flight_6E-987,flight_6E-989,flight_6E-992,flight_6E-994,flight_6E-995,flight_6E-998,flight_AI-401,flight_AI-402,flight_AI-403,flight_AI-406,flight_AI-407,flight_AI-409,flight_AI-411,flight_AI-415,flight_AI-420,flight_AI-423,flight_AI-424,flight_AI-429,flight_AI-430,flight_AI-431,flight_AI-433,flight_AI-435,flight_AI-437,flight_AI-439,flight_AI-440,flight_AI-441,flight_AI-442,flight_AI-451,flight_AI-453,flight_AI-459,flight_AI-465,flight_AI-467,flight_AI-469,flight_AI-471,flight_AI-473,flight_AI-475,flight_AI-479,flight_AI-481,flight_AI-483,flight_AI-485,flight_AI-487,flight_AI-489,flight_AI-491,flight_AI-493,flight_AI-499,flight_AI-501,flight_AI-502,flight_AI-503,flight_AI-504,flight_AI-505,flight_AI-506,flight_AI-507,flight_AI-508,flight_AI-509,flight_AI-512,flight_AI-515,flight_AI-516,flight_AI-523,flight_AI-525,flight_AI-526,flight_AI-531,flight_AI-537,flight_AI-538,flight_AI-539,flight_AI-540,flight_AI-541,flight_AI-542,flight_AI-543,flight_AI-544,flight_AI-545,flight_AI-546,flight_AI-549,flight_AI-551,flight_AI-559,flight_AI-560,flight_AI-563,flight_AI-564,flight_AI-565,flight_AI-569,flight_AI-570,flight_AI-573,flight_AI-583,flight_AI-601,flight_AI-603,flight_AI-604,flight_AI-607,flight_AI-610,flight_AI-611,flight_AI-615,flight_AI-616,flight_AI-619,flight_AI-620,flight_AI-623,flight_AI-624,flight_AI-625,flight_AI-627,flight_AI-629,flight_AI-631,flight_AI-633,flight_AI-635,flight_AI-636,flight_AI-637,flight_AI-639,flight_AI-640,flight_AI-641,flight_AI-643,flight_AI-645,flight_AI-649,flight_AI-651,flight_AI-652,flight_AI-655,flight_AI-657,flight_AI-660,flight_AI-663,flight_AI-665,flight_AI-667,flight_AI-669,flight_AI-671,flight_AI-672,flight_AI-673,flight_AI-675,flight_AI-676,flight_AI-678,flight_AI-679,flight_AI-681,flight_AI-683,flight_AI-685,flight_AI-687,flight_AI-688,flight_AI-695,flight_AI-698,flight_AI-713,flight_AI-715,flight_AI-721,flight_AI-729,flight_AI-732,flight_AI-738,flight_AI-743,flight_AI-745,flight_AI-747,flight_AI-748,flight_AI-762,flight_AI-763,flight_AI-764,flight_AI-765,flight_AI-766,flight_AI-767,flight_AI-768,flight_AI-770,flight_AI-771,flight_AI-772,flight_AI-773,flight_AI-774,flight_AI-775,flight_AI-776,flight_AI-780,flight_AI-781,flight_AI-787,flight_AI-801,flight_AI-803,flight_AI-804,flight_AI-805,flight_AI-806,flight_AI-807,flight_AI-808,flight_AI-809,flight_AI-811,flight_AI-837,flight_AI-838,flight_AI-839,flight_AI-840,flight_AI-861,flight_AI-864,flight_AI-865,flight_AI-867,flight_AI-868,flight_AI-877,flight_AI-879,flight_AI-883,flight_AI-885,flight_AI-887,flight_AI-888,flight_AI-889,flight_AI-891,flight_AI-895,flight_AI-9015,flight_AI-9017,flight_AI-9030,flight_AI-9501,flight_AI-9505,flight_AI-9517,flight_AI-9518,flight_AI-9547,flight_AI-9609,flight_AI-9643,flight_AI-9645,flight_AI-9657,flight_AI-9720,flight_AI-9741,flight_AI-9745,flight_AI-9755,flight_AI-9809,flight_AI-9843,flight_AI-9857,flight_AI-9875,flight_AI-9876,flight_AI-9881,flight_AI-9885,flight_AI-9887,flight_AI-9891,flight_AI-9893,flight_AI-9894,flight_AI-9911,flight_AI-9915,flight_AI-9919,flight_AI-9921,flight_AI-9925,flight_AI-9927,flight_AI-9928,flight_AI-9929,flight_AI-9931,flight_AI-9937,flight_AI-9939,flight_AI-9991,flight_G8-101,flight_G8-1010,flight_G8-102,flight_G8-103,flight_G8-105,flight_G8-107,flight_G8-108,flight_G8-113,flight_G8-116,flight_G8-1171,flight_G8-118,flight_G8-119,flight_G8-121,flight_G8-123,flight_G8-125,flight_G8-131,flight_G8-133,flight_G8-1404,flight_G8-143,flight_G8-145,flight_G8-146,flight_G8-151,flight_G8-153,flight_G8-165,flight_G8-171,flight_G8-173,flight_G8-188,flight_G8-191,flight_G8-194,flight_G8-199,flight_G8-203,flight_G8-207,flight_G8-209,flight_G8-211,flight_G8-213,flight_G8-2201,flight_G8-2231,flight_G8-227,flight_G8-231,flight_G8-237,flight_G8-2401,flight_G8-2403,flight_G8-241,flight_G8-2411,flight_G8-2417,flight_G8-244,flight_G8-2440,flight_G8-2501,flight_G8-2502,flight_G8-2504,flight_G8-2506,flight_G8-2508,flight_G8-2509,flight_G8-2511,flight_G8-2513,flight_G8-2601,flight_G8-2605,flight_G8-2606,flight_G8-2607,flight_G8-2609,flight_G8-266,flight_G8-268,flight_G8-275,flight_G8-283,flight_G8-285,flight_G8-286,flight_G8-287,flight_G8-292,flight_G8-294,flight_G8-295,flight_G8-297,flight_G8-299,flight_G8-300,flight_G8-302,flight_G8-303,flight_G8-304,flight_G8-305,flight_G8-306,flight_G8-312,flight_G8-317,flight_G8-3184,flight_G8-319,flight_G8-320,flight_G8-321,flight_G8-322,flight_G8-323,flight_G8-325,flight_G8-327,flight_G8-329,flight_G8-330,flight_G8-331,flight_G8-334,flight_G8-336,flight_G8-338,flight_G8-339,flight_G8-341,flight_G8-345,flight_G8-346,flight_G8-347,flight_G8-349,flight_G8-351,flight_G8-354,flight_G8-357,flight_G8-363,flight_G8-364,flight_G8-365,flight_G8-371,flight_G8-374,flight_G8-381,flight_G8-382,flight_G8-383,flight_G8-384,flight_G8-385,flight_G8-387,flight_G8-390,flight_G8-391,flight_G8-392,flight_G8-393,flight_G8-395,flight_G8-397,flight_G8-398,flight_G8-399,flight_G8-401,flight_G8-403,flight_G8-404,flight_G8-405,flight_G8-422,flight_G8-423,flight_G8-424,flight_G8-426,flight_G8-451,flight_G8-461,flight_G8-501,flight_G8-503,flight_G8-504,flight_G8-505,flight_G8-506,flight_G8-509,flight_G8-510,flight_G8-511,flight_G8-512,flight_G8-513,flight_G8-515,flight_G8-517,flight_G8-518,flight_G8-519,flight_G8-520,flight_G8-530,flight_G8-532,flight_G8-537,flight_G8-551,flight_G8-571,flight_G8-575,flight_G8-602,flight_G8-625,flight_G8-626,flight_G8-661,flight_G8-676,flight_G8-681,flight_G8-701,flight_G8-704,flight_G8-705,flight_G8-713,flight_G8-717,flight_G8-719,flight_G8-7533,flight_G8-7534,flight_G8-7535,flight_G8-7536,flight_G8-7537,flight_G8-7538,flight_G8-7541,flight_G8-7542,flight_G8-7543,flight_G8-7545,flight_G8-7546,flight_G8-7547,flight_G8-7548,flight_G8-7549,flight_G8-7553,flight_G8-7555,flight_G8-7556,flight_G8-7557,flight_G8-7559,flight_G8-7560,flight_G8-7561,flight_G8-7562,flight_G8-787,flight_G8-789,flight_G8-790,flight_G8-791,flight_G8-792,flight_G8-801,flight_G8-803,flight_G8-805,flight_G8-806,flight_G8-808,flight_G8-812,flight_G8-813,flight_G8-815,flight_G8-873,flight_G8-911,flight_G8-9110,flight_G8-917,flight_G8-962,flight_I5-1228,flight_I5-1229,flight_I5-1321,flight_I5-1426,flight_I5-1427,flight_I5-1451,flight_I5-1454,flight_I5-1517,flight_I5-1518,flight_I5-1528,flight_I5-1529,flight_I5-1530,flight_I5-1531,flight_I5-1540,flight_I5-1543,flight_I5-1561,flight_I5-1562,flight_I5-1563,flight_I5-1564,flight_I5-1566,flight_I5-1569,flight_I5-1576,flight_I5-1621,flight_I5-1622,flight_I5-1727,flight_I5-1731,flight_I5-1780,flight_I5-1782,flight_I5-1783,flight_I5-1982,flight_I5-1983,flight_I5-2392,flight_I5-2461,flight_I5-2462,flight_I5-2472,flight_I5-2473,flight_I5-2991,flight_I5-319,flight_I5-330,flight_I5-334,flight_I5-336,flight_I5-338,flight_I5-339,flight_I5-360,flight_I5-361,flight_I5-371,flight_I5-410,flight_I5-423,flight_I5-471,flight_I5-482,flight_I5-510,flight_I5-517,flight_I5-5204,flight_I5-5205,flight_I5-5402,flight_I5-5405,flight_I5-5406,flight_I5-541,flight_I5-547,flight_I5-548,flight_I5-550,flight_I5-552,flight_I5-556,flight_I5-557,flight_I5-559,flight_I5-582,flight_I5-583,flight_I5-588,flight_I5-589,flight_I5-592,flight_I5-620,flight_I5-631,flight_I5-678,flight_I5-710,flight_I5-711,flight_I5-713,flight_I5-721,flight_I5-722,flight_I5-735,flight_I5-736,flight_I5-737,flight_I5-740,flight_I5-741,flight_I5-744,flight_I5-747,flight_I5-749,flight_I5-764,flight_I5-766,flight_I5-767,flight_I5-768,flight_I5-773,flight_I5-775,flight_I5-779,flight_I5-783,flight_I5-784,flight_I5-787,flight_I5-788,flight_I5-791,flight_I5-792,flight_I5-798,flight_I5-818,flight_I5-819,flight_I5-820,flight_I5-821,flight_I5-829,flight_I5-830,flight_I5-881,flight_I5-892,flight_I5-941,flight_I5-942,flight_I5-972,flight_I5-974,flight_I5-991,flight_I5-992,flight_I5-996,flight_SG-1031,flight_SG-1032,flight_SG-1054,flight_SG-1056,flight_SG-1057,flight_SG-1058,flight_SG-1059,flight_SG-1061,flight_SG-1062,flight_SG-1063,flight_SG-107,flight_SG-1071,flight_SG-1072,flight_SG-1074,flight_SG-1077,flight_SG-1089,flight_SG-1090,flight_SG-1091,flight_SG-1092,flight_SG-136,flight_SG-143,flight_SG-163,flight_SG-191,flight_SG-197,flight_SG-198,flight_SG-209,flight_SG-223,flight_SG-2277,flight_SG-241,flight_SG-242,flight_SG-2508,flight_SG-251,flight_SG-254,flight_SG-263,flight_SG-264,flight_SG-2643,flight_SG-2697,flight_SG-274,flight_SG-276,flight_SG-292,flight_SG-2976,flight_SG-3002,flight_SG-3023,flight_SG-3027,flight_SG-3229,flight_SG-3233,flight_SG-3239,flight_SG-3248,flight_SG-327,flight_SG-3281,flight_SG-3283,flight_SG-329,flight_SG-3321,flight_SG-337,flight_SG-339,flight_SG-343,flight_SG-3440,flight_SG-349,flight_SG-3564,flight_SG-366,flight_SG-3719,flight_SG-3723,flight_SG-3725,flight_SG-3728,flight_SG-3831,flight_SG-3832,flight_SG-3835,flight_SG-3839,flight_SG-387,flight_SG-388,flight_SG-389,flight_SG-390,flight_SG-395,flight_SG-4003,flight_SG-4005,flight_SG-4009,flight_SG-401,flight_SG-4010,flight_SG-4025,flight_SG-4027,flight_SG-4031,flight_SG-406,flight_SG-415,flight_SG-438,flight_SG-4417,flight_SG-455,flight_SG-467,flight_SG-468,flight_SG-475,flight_SG-480,flight_SG-487,flight_SG-488,flight_SG-489,flight_SG-5002,flight_SG-5006,flight_SG-5007,flight_SG-5012,flight_SG-5013,flight_SG-5018,flight_SG-5019,flight_SG-5025,flight_SG-5067,flight_SG-5068,flight_SG-5069,flight_SG-5072,flight_SG-5073,flight_SG-5074,flight_SG-5075,flight_SG-5079,flight_SG-5088,flight_SG-5091,flight_SG-5092,flight_SG-5093,flight_SG-5094,flight_SG-516,flight_SG-517,flight_SG-520,flight_SG-531,flight_SG-534,flight_SG-535,flight_SG-6001,flight_SG-6003,flight_SG-6005,flight_SG-6006,flight_SG-6016,flight_SG-6017,flight_SG-6018,flight_SG-6027,flight_SG-611,flight_SG-612,flight_SG-634,flight_SG-635,flight_SG-649,flight_S

### 사이킷런으로 원핫 인코딩하기 - OneHotEncoder 클래스

In [102]:
df = df_origin.copy()


oh = OneHotEncoder()
# fit_transform()에는 2차원 배열이 들어가야 한다.
df['class'].values

<ArrowStringArray>
[ 'Economy',  'Economy',  'Economy',  'Economy',  'Economy',  'Economy',
  'Economy',  'Economy',  'Economy',  'Economy',
 ...
 'Business', 'Business', 'Business', 'Business', 'Business', 'Business',
 'Business', 'Business', 'Business', 'Business']
Length: 300153, dtype: str

In [103]:
df['class'].values.reshape(-1, 1)

NotImplementedError: <class 'pandas.arrays.ArrowStringArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.

In [ ]:
oh.fit_transform(df['class'].values.reshape(-1,1)).toarray()

NotImplementedError: <class 'pandas.arrays.ArrowStringArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.

- onHotEncoder는 배열을 반환(array)
- 왜 바로 데이터프레임에 반영되지 않는가?
    - 머신러닝 파이프라인에 바로 연결해서 train/test 데이터에 동일한 인코딩 규칙을 일관되게 적용하기 위해 설계된 도구이기 때문
    - 단순 EDA/전처리용으로는 get_dummies가 훨씬 간편하다.
    - 실제 머신러닝 모델링에서는 OneHotEncoder를 사용하는 경우도 많다.